package mud.items;

import mud.chance.Roller;

/**
 * Weapons can be used by players or NPCs to deal damage to other characters.
 *
 * @author Japhez
 */
public class Weapon extends Item {

    private WeaponType weaponType;
    private int numberOfDice;
    private int numberOfSides;
    private static Roller roller = new Roller();

    public Weapon(int weight, int value, String shortName, String longName, int numberOfDice, int numberOfSides) {
        super(weight, value, shortName, longName);
        this.numberOfDice = numberOfDice;
        this.numberOfSides = numberOfSides;
    }

    /**
     * @return a random damage roll generated by this weapon
     */
    public int getDamage() {
        return roller.rollDice(numberOfDice, numberOfSides);
    }

    public int getNumberOfDice() {
        return numberOfDice;
    }

    public void setNumberOfDice(int numberOfDice) {
        this.numberOfDice = numberOfDice;
    }

    public int getNumberOfSides() {
        return numberOfSides;
    }

    public void setNumberOfSides(int numberOfSides) {
        this.numberOfSides = numberOfSides;
    }

    public WeaponType getWeaponType() {
        return weaponType;
    }

    public void setWeaponType(WeaponType weaponType) {
        this.weaponType = weaponType;
    }

    public enum WeaponType {

        ONE_HANDED, TWO_HANDED
    }

    public enum WeaponSlot {

        LEFT_HAND, RIGHT_HAND
    }
}
